# Generated by Django 2.1 on 2018-08-17 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_auto_20180815_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userword',
            name='down_vote',
            field=models.ManyToManyField(blank=True, related_name='down_vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userword',
            name='up_vote',
            field=models.ManyToManyField(blank=True, related_name='up_vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
