# Generated by Django 2.1 on 2018-08-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_auto_20180812_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
