# Generated by Django 2.1 on 2018-08-14 23:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words', '0004_auto_20180813_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='down_vote',
        ),
        migrations.AddField(
            model_name='word',
            name='down_vote',
            field=models.ManyToManyField(related_name='down_vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='word',
            name='up_vote',
        ),
        migrations.AddField(
            model_name='word',
            name='up_vote',
            field=models.ManyToManyField(related_name='up_vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
