# Generated by Django 2.1 on 2018-08-15 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words', '0005_auto_20180814_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('example', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('down_vote', models.ManyToManyField(related_name='down_vote', to=settings.AUTH_USER_MODEL)),
                ('up_vote', models.ManyToManyField(related_name='up_vote', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='down_vote',
        ),
        migrations.RemoveField(
            model_name='word',
            name='up_vote',
        ),
        migrations.RemoveField(
            model_name='word',
            name='user',
        ),
        migrations.AlterField(
            model_name='wordtimestamp',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word', to='words.UserWord'),
        ),
        migrations.DeleteModel(
            name='Word',
        ),
        migrations.AddField(
            model_name='generalword',
            name='words',
            field=models.ManyToManyField(to='words.UserWord'),
        ),
    ]
