# Generated by Django 2.1 on 2018-08-15 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_auto_20180815_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalword',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='wordtimestamp',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_word', to='words.GeneralWord'),
        ),
    ]
